if (WIN32)
    add_compile_options(/utf-8)
    if (NOT CMAKE_TOOLCHAIN_FILE)
        if (NOT DEFINED ENV{VCPKG_ROOT})
            message(FATAL_ERROR "Environment variable VCPKG_ROOT not set; please set it to your vcpkg root path.")
        endif ()
        set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE FILEPATH "Vcpkg toolchain file")
    endif ()
endif ()